-- Snowflake Table Creation Scripts for Organization Onboarding System
-- Run these scripts in Snowflake to create the required tables

-- =====================================================
-- ORGANIZATIONS TABLE
-- Stores organization registration and plan information
-- =====================================================
CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
    ID VARCHAR(36) PRIMARY KEY,
    ORGANIZATION_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(50),
    WEBSITE VARCHAR(255),
    ADDRESS VARCHAR(500),
    HAS_ACTIVE_PLAN BOOLEAN DEFAULT FALSE,
    PLAN_TYPE VARCHAR(50),
    PLAN_START_DATE TIMESTAMP_NTZ,
    PLAN_END_DATE TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS IDX_ORG_EMAIL ON ORGANIZATIONS(EMAIL);

-- =====================================================
-- PAYMENTS TABLE
-- Stores payment transaction records for organizations
-- =====================================================
CREATE TABLE IF NOT EXISTS PAYMENTS (
    ID VARCHAR(36) PRIMARY KEY,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    RAZORPAY_ORDER_ID VARCHAR(255) NOT NULL,
    RAZORPAY_PAYMENT_ID VARCHAR(255),
    RAZORPAY_SIGNATURE VARCHAR(255),
    AMOUNT NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR(10) DEFAULT 'INR',
    PLAN_TYPE VARCHAR(50) NOT NULL,
    PLAN_DURATION_MONTHS INTEGER NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'pending',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATIONS(ID)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_ORG_ID ON PAYMENTS(ORGANIZATION_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_ORDER_ID ON PAYMENTS(RAZORPAY_ORDER_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_STATUS ON PAYMENTS(STATUS);